import { useEffect,useMemo,useState } from 'react';
import { api } from '../../lib/api';
import { Badge,Empty,Notice,Panel } from '../../components/StateViews';
import { Icon } from '../../components/Icons';

const actionLabels:Record<string,string>={login:'Login',logout:'Logout',login_failed:'Falha de login',create:'Criação',update:'Alteração',delete:'Exclusão',archive:'Arquivamento',restore:'Restauração',reorder:'Reordenação'};
const actionTone=(action:string):'neutral'|'red'|'green'|'yellow'|'blue'=>action==='login_failed'||action==='delete'?'red':action==='create'||action==='restore'?'green':action==='archive'?'yellow':action==='login'?'blue':'neutral';
function metadata(value:string){try{return JSON.parse(value||'{}')}catch{return {}}}

export function System(){
  const [logs,setLogs]=useState<any[]>([]);const [error,setError]=useState('');const [query,setQuery]=useState('');const [action,setAction]=useState('all');const [entity,setEntity]=useState('all');const [selected,setSelected]=useState<any|null>(null);const [loading,setLoading]=useState(false);
  const load=async()=>{setLoading(true);setError('');try{const r=await api<any>('/api/admin/audit?limit=500');setLogs(r.results||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load();},[]);
  const actions=useMemo(()=>[...new Set(logs.map(x=>x.action).filter(Boolean))].sort(),[logs]);
  const entities=useMemo(()=>[...new Set(logs.map(x=>x.entity_type).filter(Boolean))].sort(),[logs]);
  const filtered=useMemo(()=>logs.filter(x=>(action==='all'||x.action===action)&&(entity==='all'||x.entity_type===entity)&&(!query||`${x.action} ${x.entity_type||''} ${x.entity_id||''} ${x.metadata_json||''}`.toLowerCase().includes(query.toLowerCase()))),[logs,query,action,entity]);
  const lastLogin=logs.find(x=>x.action==='login');const failures=logs.filter(x=>x.action==='login_failed').length;const mutations=logs.filter(x=>['create','update','delete','archive','restore','reorder'].includes(x.action)).length;
  return <div className="module-stack"><div className="governance-grid"><article><span><Icon name="system"/></span><div><small>SESSÕES</small><strong>Protegidas</strong><p>Cookie HttpOnly, SameSite Strict, HMAC e expiração automática.</p></div></article><article><span><Icon name="refresh"/></span><div><small>VERSIONAMENTO</small><strong>Reversível</strong><p>Seções e eventos preservam versões antes de alterações estruturais.</p></div></article><article><span><Icon name="activity"/></span><div><small>AUDITORIA</small><strong>{logs.length} ações</strong><p>{mutations} mutações nas {logs.length} ações mais recentes carregadas.</p></div></article><article><span><Icon name="check"/></span><div><small>ÚLTIMO ACESSO</small><strong>{lastLogin?new Date(lastLogin.created_at).toLocaleDateString('pt-BR'):'—'}</strong><p>{failures} tentativas inválidas no recorte atual.</p></div></article></div>
    <Panel title="Log de auditoria" eyebrow="Governança" description="Rastro administrativo das alterações realizadas no ecossistema GTRZ." action={<button onClick={load} disabled={loading}><Icon name="refresh" size={15}/>{loading?'Atualizando…':'Atualizar'}</button>}>
      {error&&<Notice tone="error">{error}</Notice>}
      <div className="toolbar audit-toolbar"><label className="search-box"><Icon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar ação, entidade ou ID…"/></label><select value={action} onChange={e=>setAction(e.target.value)}><option value="all">Todas as ações</option>{actions.map(x=><option key={x} value={x}>{actionLabels[x]||x}</option>)}</select><select value={entity} onChange={e=>setEntity(e.target.value)}><option value="all">Todas as entidades</option>{entities.map(x=><option key={x} value={x}>{x}</option>)}</select><span>{filtered.length} registros</span></div>
      {filtered.length?<div className="audit-table"><div className="audit-row audit-head"><span>Data</span><span>Ação</span><span>Entidade</span><span>Identificador</span><span></span></div>{filtered.map(x=><button type="button" className="audit-row" key={x.id} onClick={()=>setSelected(x)}><time>{new Date(x.created_at).toLocaleString('pt-BR')}</time><span><Badge tone={actionTone(x.action)}>{actionLabels[x.action]||x.action}</Badge></span><strong>{x.entity_type||'sistema'}</strong><code>{x.entity_id||'—'}</code><Icon name="arrow" size={14}/></button>)}</div>:<Empty icon="activity">Nenhum registro corresponde aos filtros.</Empty>}
    </Panel>
    {selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)}><aside className="audit-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><Badge tone={actionTone(selected.action)}>{actionLabels[selected.action]||selected.action}</Badge><h3>Detalhes da ação</h3></div><button className="icon-button" onClick={()=>setSelected(null)}><Icon name="close"/></button></div><div className="asset-facts audit-facts"><div><span>Data</span><strong>{new Date(selected.created_at).toLocaleString('pt-BR')}</strong></div><div><span>Entidade</span><strong>{selected.entity_type||'sistema'}</strong></div><div><span>ID</span><code>{selected.entity_id||'—'}</code></div><div><span>Ator</span><code>{selected.actor_user_id||'sessão administrativa'}</code></div></div><label className="field"><span>Metadados registrados</span><textarea className="code-editor tall" readOnly value={JSON.stringify(metadata(selected.metadata_json),null,2)}/></label><p className="hint">O log é somente leitura no Control. Ele existe para rastrear operações administrativas e diagnosticar alterações.</p></aside></div>}
  </div>;
}
