INSERT OR IGNORE INTO page_sections(id,page_id,type,position,enabled,config_json) VALUES
('home_hero','page_home','hero',10,1,'{}'),('home_about','page_home','about',20,1,'{}'),('home_rhythms','page_home','rhythms',30,1,'{}'),('home_differentials','page_home','differentials',40,1,'{}'),('home_events','page_home','events',50,1,'{}'),('home_team','page_home','team',60,1,'{}'),('home_instagram','page_home','instagram',90,1,'{}'),('home_contact','page_home','contact',100,1,'{}');

INSERT OR IGNORE INTO section_localizations(section_id,locale,content_json) VALUES
('home_hero','pt-BR','{"eyebrow":"Produção · cultura · experiência","title":"EXPERIÊNCIAS QUE TÊM IDENTIDADE.","body":"A GTRZ produz festas e experiências culturais com linguagem própria. Nascemos na Venezuela, fomos criados por venezuelanos e hoje, no Brasil, somos construídos por venezuelanos e brasileiros.","originEyebrow":"DA VENEZUELA PARA O BRASIL","originTitle":"DUAS CULTURAS. UMA MARCA.","originBody":"Nossa história cruza países, sotaques e referências. A GTRZ carrega sua origem venezuelana e cresce no Brasil com uma construção feita também por brasileiros."}'),
('home_hero','es','{"eyebrow":"Producción · cultura · experiencia","title":"EXPERIENCIAS CON IDENTIDAD.","body":"GTRZ produce fiestas y experiencias culturales con lenguaje propio. Nacimos en Venezuela, fuimos creados por venezolanos y hoy, en Brasil, somos construidos por venezolanos y brasileños.","originEyebrow":"DE VENEZUELA A BRASIL","originTitle":"DOS CULTURAS. UNA MARCA.","originBody":"Nuestra historia cruza países, acentos y referencias. GTRZ lleva su origen venezolano y crece en Brasil con una construcción hecha también por brasileños."}'),
('home_about','pt-BR','{"eyebrow":"Sobre a GTRZ","title":"NÃO É SÓ UMA FESTA."}'),('home_about','es','{"eyebrow":"Sobre GTRZ","title":"NO ES SOLO UNA FIESTA."}'),
('home_rhythms','pt-BR','{"eyebrow":"O som da GTRZ","title":"NOSSOS RITMOS.","items":["Reggaeton","Dembow","Salsa","Merengue","Bachata","Latin Pop","Funk","Urban Mix"]}'),('home_rhythms','es','{"eyebrow":"El sonido de GTRZ","title":"NUESTROS RITMOS.","items":["Reggaeton","Dembow","Salsa","Merengue","Bachata","Latin Pop","Funk","Urban Mix"]}'),
('home_differentials','pt-BR','{"title":"NOSSOS DIFERENCIAIS."}'),('home_differentials','es','{"title":"NUESTROS DIFERENCIALES."}'),
('home_events','pt-BR','{"title":"EVENTOS."}'),('home_events','es','{"title":"EVENTOS."}'),
('home_team','pt-BR','{"title":"POR TRÁS DA GTRZ."}'),('home_team','es','{"title":"POR DETRÁS DE GTRZ."}'),
('home_instagram','pt-BR','{"title":"SIGA A GTRZ NO INSTAGRAM.","handle":"@gtrzeventos","url":"https://instagram.com/gtrzeventos"}'),('home_instagram','es','{"title":"SIGUE A GTRZ EN INSTAGRAM.","handle":"@gtrzeventos","url":"https://instagram.com/gtrzeventos"}'),
('home_contact','pt-BR','{"title":"VAMOS FAZER ACONTECER?","cta":"Falar com a GTRZ","email":"gtrzeventos@gmail.com"}'),('home_contact','es','{"title":"¿HACEMOS QUE SUCEDA?","cta":"Hablar con GTRZ","email":"gtrzeventos@gmail.com"}');
