ALTER TABLE partnership_leads ADD COLUMN partner_type TEXT;
ALTER TABLE partnership_leads ADD COLUMN legal_name TEXT;
ALTER TABLE partnership_leads ADD COLUMN trade_name TEXT;
ALTER TABLE partnership_leads ADD COLUMN tax_id TEXT;
ALTER TABLE partnership_leads ADD COLUMN segment TEXT;
ALTER TABLE partnership_leads ADD COLUMN website_url TEXT;
ALTER TABLE partnership_leads ADD COLUMN instagram_url TEXT;
ALTER TABLE partnership_leads ADD COLUMN contact_role TEXT;
ALTER TABLE partnership_leads ADD COLUMN postal_code TEXT;
ALTER TABLE partnership_leads ADD COLUMN state TEXT;
ALTER TABLE partnership_leads ADD COLUMN neighborhood TEXT;
ALTER TABLE partnership_leads ADD COLUMN street TEXT;
ALTER TABLE partnership_leads ADD COLUMN address_number TEXT;
ALTER TABLE partnership_leads ADD COLUMN complement TEXT;
ALTER TABLE partnership_leads ADD COLUMN venue_capacity INTEGER;
ALTER TABLE partnership_leads ADD COLUMN service_type TEXT;
ALTER TABLE partnership_leads ADD COLUMN service_area TEXT;
ALTER TABLE partnership_leads ADD COLUMN proposal_types_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE partnership_leads ADD COLUMN other_proposal_type TEXT;
ALTER TABLE partnership_leads ADD COLUMN proposal_title TEXT;
ALTER TABLE partnership_leads ADD COLUMN offer_text TEXT;
ALTER TABLE partnership_leads ADD COLUMN expectation_text TEXT;
ALTER TABLE partnership_leads ADD COLUMN investment_status TEXT;
ALTER TABLE partnership_leads ADD COLUMN investment_value_cents INTEGER;
ALTER TABLE partnership_leads ADD COLUMN starts_at TEXT;
ALTER TABLE partnership_leads ADD COLUMN ends_at TEXT;
ALTER TABLE partnership_leads ADD COLUMN proposal_media_id TEXT REFERENCES media_assets(id);
ALTER TABLE partnership_leads ADD COLUMN proposal_file_name TEXT;
ALTER TABLE partnership_leads ADD COLUMN presentation_url TEXT;
ALTER TABLE partnership_leads ADD COLUMN observations TEXT;
ALTER TABLE partnership_leads ADD COLUMN privacy_accepted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE partnership_leads ADD COLUMN privacy_accepted_at TEXT;
ALTER TABLE partnership_leads ADD COLUMN privacy_notice_version TEXT;
ALTER TABLE partnership_leads ADD COLUMN privacy_notice_locale TEXT;
ALTER TABLE partnership_leads ADD COLUMN privacy_notice_text TEXT;
ALTER TABLE partnership_leads ADD COLUMN next_contact_at TEXT;
ALTER TABLE partnership_leads ADD COLUMN potential_value_cents INTEGER;

CREATE INDEX IF NOT EXISTS idx_partnerships_status_created ON partnership_leads(status,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_partnerships_partner_type ON partnership_leads(partner_type);
