import { Hono } from 'hono';
import type { Env } from '../env';
import { consumePublicFormQuota, verifyTurnstile } from '../security';

export const partnershipRoutes = new Hono<{ Bindings: Env }>();
const id=()=>crypto.randomUUID();
const upper=(v:unknown,max=300)=>String(v??'').trim().replace(/\s+/g,' ').toLocaleUpperCase('pt-BR').slice(0,max);
const digits=(v:unknown)=>String(v??'').replace(/\D/g,'');
const PARTNERSHIP_NOTICE_VERSION='1.0';
const MAX_BODY_BYTES=12*1024*1024;
const defaultPartnerTypes=['LOCAL / CASA / BAR / BOATE','MARCA','EMPRESA','FORNECEDOR','PRODUTORA / PROJETO','ARTISTA / AGÊNCIA','IMPRENSA / MÍDIA','OUTRO'];
const defaultProposalTypes=['PATROCÍNIO','APOIO','LOCAÇÃO DE ESPAÇO','REALIZAÇÃO DE EVENTO','CO-PRODUÇÃO','FORNECIMENTO DE PRODUTO','FORNECIMENTO DE SERVIÇO','AÇÃO DE MARCA','DIVULGAÇÃO / MÍDIA','PERMUTA','CONTRATAÇÃO DA GTRZ','OUTRO'];
const notice=(locale:string)=>locale==='es'
?'Al enviar esta propuesta, declaro que leí y comprendí el Aviso de Privacidad y autorizo a GTRZ a tratar los datos informados para analizar la propuesta, identificar y contactar al responsable, conducir negociaciones, mantener el historial de la relación comercial y, cuando corresponda, formalizar la alianza. Los datos no serán comercializados ni utilizados para finalidades incompatibles con esta relación.'
:'Ao enviar esta proposta, declaro que li e compreendi o Aviso de Privacidade e autorizo a GTRZ a tratar os dados informados para análise da proposta, identificação e contato com o responsável, condução de negociações, manutenção do histórico de relacionamento comercial e, quando aplicável, formalização da parceria. Os dados não serão comercializados nem utilizados para finalidades incompatíveis com essa relação.';
function validEmail(v:string){return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i.test(v)&&v.length<=200}
function validCpf(raw:unknown){const cpf=digits(raw);if(cpf.length!==11||/^(\d)\1{10}$/.test(cpf))return false;const calc=(len:number)=>{let sum=0;for(let i=0;i<len;i++)sum+=Number(cpf[i])*(len+1-i);const r=(sum*10)%11;return r===10?0:r};return calc(9)===Number(cpf[9])&&calc(10)===Number(cpf[10])}
function validCnpj(raw:unknown){const c=digits(raw);if(c.length!==14||/^(\d)\1{13}$/.test(c))return false;const calc=(base:number)=>{const w=base===12?[5,4,3,2,9,8,7,6,5,4,3,2]:[6,5,4,3,2,9,8,7,6,5,4,3,2];let s=0;for(let i=0;i<base;i++)s+=Number(c[i])*(w[i]??0);const r=s%11;return r<2?0:11-r};return calc(12)===Number(c[12])&&calc(13)===Number(c[13])}
function parseMoney(v:unknown){const raw=String(v||'').replace(/[^\d,.-]/g,'').replace(/\./g,'').replace(',','.');const n=Number(raw);return Number.isFinite(n)&&n>=0?Math.round(n*100):null}
async function config(env:Env){const row=await env.DB.prepare("SELECT value_json FROM site_settings WHERE key='partnership' LIMIT 1").first<{value_json:string}>();try{const p=JSON.parse(row?.value_json||'{}');return {whatsapp:digits(p.whatsapp),partnerTypes:Array.isArray(p.partnerTypes)&&p.partnerTypes.length?p.partnerTypes.map((x:unknown)=>upper(x,100)):defaultPartnerTypes,proposalTypes:Array.isArray(p.proposalTypes)&&p.proposalTypes.length?p.proposalTypes.map((x:unknown)=>upper(x,100)):defaultProposalTypes}}catch{return {whatsapp:'',partnerTypes:defaultPartnerTypes,proposalTypes:defaultProposalTypes}}}

partnershipRoutes.get('/config',async c=>c.json({...await config(c.env),privacyNoticeVersion:PARTNERSHIP_NOTICE_VERSION},200,{'cache-control':'public,max-age=120,s-maxage=300'}));

partnershipRoutes.post('/',async c=>{
  const contentLength=Number(c.req.header('content-length')||0);if(Number.isFinite(contentLength)&&contentLength>MAX_BODY_BYTES)return c.json({error:'payload_too_large'},413);
  const contentType=c.req.header('content-type')||'';if(!contentType.includes('multipart/form-data'))return c.json({error:'multipart_required'},415);
  const form=await c.req.formData();const body:Record<string,unknown>={};form.forEach((v,k)=>{if(!(v instanceof File))body[k]=v});
  const partnerType=upper(body.partnerType,100),contactName=upper(body.contactName,160),contactRole=upper(body.contactRole,120),whatsapp=digits(body.whatsapp),email=String(body.email||'').trim().toLowerCase(),tradeName=upper(body.tradeName,180),legalName=upper(body.legalName,200),taxId=digits(body.taxId),segment=upper(body.segment,120),websiteUrl=String(body.websiteUrl||'').trim().slice(0,1000),instagramUrl=String(body.instagramUrl||'').trim().slice(0,200),state=upper(body.state,2),city=upper(body.city,120),postalCode=digits(body.postalCode).slice(0,8),neighborhood=upper(body.neighborhood,120),street=upper(body.street,180),addressNumber=upper(body.addressNumber,30),complement=upper(body.complement,160),serviceType=upper(body.serviceType,160),serviceArea=upper(body.serviceArea,160),venueCapacity=Math.max(0,Math.min(9999999,Number(digits(body.venueCapacity)||0)))||null,proposalTitle=upper(body.proposalTitle,180),message=upper(body.message,1200),offerText=upper(body.offerText,1200),expectationText=upper(body.expectationText,1200),investmentStatus=upper(body.investmentStatus,20),investmentValueCents=parseMoney(body.investmentValue),startsAt=String(body.startsAt||'').slice(0,10)||null,endsAt=String(body.endsAt||'').slice(0,10)||null,presentationUrl=String(body.presentationUrl||'').trim().slice(0,1000),observations=upper(body.observations,1000),otherProposalType=upper(body.otherProposalType,180),privacyAccepted=String(body.privacyAccepted||'')==='1',privacyLocale=String(body.privacyNoticeLocale||'pt-BR')==='es'?'es':'pt-BR',privacyVersion=String(body.privacyNoticeVersion||'');
  if(String(body.observations||'').length>1000||String(body.message||'').length>1200||String(body.offerText||'').length>1200||String(body.expectationText||'').length>1200)return c.json({error:'text_too_long'},413);
  const proposalTypes=[...new Set(form.getAll('proposalTypes').map(v=>upper(v,100)).filter(Boolean))].slice(0,20);
  const cfg=await config(c.env);const local=partnerType.includes('LOCAL / CASA'),supplier=partnerType.includes('FORNECEDOR');
  if(!cfg.partnerTypes.includes(partnerType)||proposalTypes.some(x=>!cfg.proposalTypes.includes(x)))return c.json({error:'invalid_option'},400);
  if(!contactName||contactName.length<5||/\d/.test(contactName)||!contactRole||whatsapp.length!==11||!validEmail(email)||!tradeName||!segment||!state||!city||!proposalTitle||!message||!offerText||!expectationText||!proposalTypes.length||!['SIM','NÃO','A DEFINIR'].includes(investmentStatus))return c.json({error:'invalid_form'},400);
  if(taxId&&!(taxId.length===11?validCpf(taxId):taxId.length===14&&validCnpj(taxId)))return c.json({error:'invalid_tax_id'},400);
  if(local&&(postalCode.length!==8||!neighborhood||!street||!addressNumber))return c.json({error:'invalid_address'},400);
  if(supplier&&(!serviceType||!serviceArea))return c.json({error:'supplier_details_required'},400);
  if(proposalTypes.includes('OUTRO')&&!otherProposalType)return c.json({error:'other_proposal_required'},400);
  if(startsAt&&endsAt&&endsAt<startsAt)return c.json({error:'invalid_period'},400);
  if(!privacyAccepted||privacyVersion!==PARTNERSHIP_NOTICE_VERSION)return c.json({error:'privacy_required'},400);
  const turnstileToken=String(body.turnstileToken||'')||undefined;
  if(!(await verifyTurnstile(c,turnstileToken)))return c.json({error:'challenge_failed'},400);if(!(await consumePublicFormQuota(c,'partnership')))return c.json({error:'rate_limited'},429);
  let proposalMediaId:string|null=null,proposalFileName:string|null=null;const file=form.get('proposalFile');if(file instanceof File&&file.size>0){if(file.size>10*1024*1024)return c.json({error:'proposal_too_large'},400);if(file.type!=='application/pdf')return c.json({error:'proposal_pdf_only'},415);const bytes=new Uint8Array(await file.arrayBuffer());if(!(bytes[0]===0x25&&bytes[1]===0x50&&bytes[2]===0x44&&bytes[3]===0x46))return c.json({error:'proposal_pdf_only'},415);proposalMediaId=id();proposalFileName=upper(file.name,240);const key=`partnerships/${new Date().toISOString().slice(0,7)}/${proposalMediaId}.pdf`;await c.env.MEDIA.put(key,bytes,{httpMetadata:{contentType:'application/pdf'},customMetadata:{assetId:proposalMediaId,kind:'partnership-proposal'}});await c.env.DB.prepare('INSERT INTO media_assets(id,r2_key,mime_type,file_name,size_bytes) VALUES(?,?,?,?,?)').bind(proposalMediaId,key,'application/pdf',file.name,file.size).run()}
  const leadId=id();await c.env.DB.prepare(`INSERT INTO partnership_leads(id,contact_name,company_name,partnership_type,email,whatsapp,city,message,source,campaign,partner_type,legal_name,trade_name,tax_id,segment,website_url,instagram_url,contact_role,postal_code,state,neighborhood,street,address_number,complement,venue_capacity,service_type,service_area,proposal_types_json,other_proposal_type,proposal_title,offer_text,expectation_text,investment_status,investment_value_cents,starts_at,ends_at,proposal_media_id,proposal_file_name,presentation_url,observations,privacy_accepted,privacy_accepted_at,privacy_notice_version,privacy_notice_locale,privacy_notice_text) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,CURRENT_TIMESTAMP,?,?,?)`)
    .bind(leadId,contactName,tradeName,proposalTypes[0],email,whatsapp,city,message,String(body.source||'').slice(0,160)||null,String(body.campaign||'').slice(0,160)||null,partnerType,legalName||null,tradeName,taxId||null,segment,websiteUrl||null,instagramUrl||null,contactRole,postalCode||null,state,neighborhood||null,street||null,addressNumber||null,complement||null,venueCapacity,serviceType||null,serviceArea||null,JSON.stringify(proposalTypes),otherProposalType||null,proposalTitle,offerText,expectationText,investmentStatus,investmentValueCents,startsAt,endsAt,proposalMediaId,proposalFileName,presentationUrl||null,observations||null,PARTNERSHIP_NOTICE_VERSION,privacyLocale,notice(privacyLocale)).run();
  return c.json({ok:true,id:leadId,whatsapp:cfg.whatsapp},201);
});