import type { Locale, SiteSettings } from './cms';

export const publicCopyDefaults:Record<Locale,Record<string,Record<string,string>>>={
  'pt-BR':{
    freelancerPage:{seoTitle:'Trabalhe conosco — GTRZ',eyebrow:'GTRZ · FREELANCERS',title:'TRABALHE COM A GENTE.',intro:'Cadastre-se no nosso banco de profissionais para futuras produções. O cadastro não representa promessa de contratação.',nameLabel:'Nome completo',whatsappLabel:'WhatsApp',emailLabel:'E-mail',cityLabel:'Cidade',stateLabel:'Estado',instagramLabel:'Instagram',rolesLabel:'Áreas de atuação',rolesPlaceholder:'Produção, foto, bar, design...',portfolioLabel:'Portfólio',portfolioPlaceholder:'https://',availabilityLabel:'Disponibilidade / observações',submitLabel:'Enviar cadastro',successMessage:'Cadastro recebido. A GTRZ entrará em contato quando houver uma oportunidade compatível.',errorMessage:'Não foi possível enviar. Tente novamente.'},
    partnershipPage:{seoTitle:'Parcerias — GTRZ',eyebrow:'GTRZ · PARCERIAS',title:'VAMOS CONSTRUIR JUNTOS.',intro:'Casas, marcas, artistas, fornecedores e projetos que queiram construir uma experiência com a GTRZ.',contactNameLabel:'Seu nome',companyNameLabel:'Empresa / projeto',typeLabel:'Tipo de parceria',typePlaceholder:'—',venueOption:'Casa / espaço',brandOption:'Marca / patrocínio',artistOption:'Artista / projeto cultural',supplierOption:'Fornecedor',otherOption:'Outro',cityLabel:'Cidade',emailLabel:'E-mail',whatsappLabel:'WhatsApp',messageLabel:'Conte a ideia',submitLabel:'Enviar proposta',successMessage:'Proposta recebida. Nossa equipe vai analisar.',errorMessage:'Não foi possível enviar. Tente novamente.'},
    eventPage:{backLabel:'GTRZ',dateLabel:'DATA',venueLabel:'LOCAL',aboutLabel:'Sobre o evento',lineupEyebrow:'GTRZ',lineupTitle:'LINE-UP.',ticketsEyebrow:'Ingressos',ticketsTitle:'ESCOLHA SEU INGRESSO.',availableLabel:'DISPONÍVEL',draftLabel:'EM BREVE',soldOutLabel:'ESGOTADO',closedLabel:'ENCERRADO',buyLabel:'Comprar',noTickets:'Os ingressos ainda não estão disponíveis.',notFoundTitle:'ESTE EVENTO NÃO ESTÁ DISPONÍVEL.',notFoundCta:'VOLTAR PARA A GTRZ'},
    popup:{multiHeader:'Eventos GTRZ disponíveis',singleHeader:'Tem evento ativo na GTRZ',closeLabel:'Fechar',eyebrow:'Agenda aberta',multiTitleLine1:'TEM GTRZ',multiTitleLine2:'EM MAIS DE UMA',multiTitleAccent:'CIDADE.',singleTitleLine1:'TEM GTRZ',singleTitleLine2:'NA SUA',singleTitleAccent:'CIDADE.',multiBody:'Escolha a cidade e entre direto na página do evento.',singleFallbackBody:'Confira data, local e ingressos disponíveis.',soldOutLabel:'Esgotado',eventCta:'Ver evento e ingressos',continueLabel:'Continuar no institucional'}
  },
  es:{
    freelancerPage:{seoTitle:'Freelancers — GTRZ',eyebrow:'GTRZ · FREELANCERS',title:'TRABAJA CON NOSOTROS.',intro:'Regístrate en nuestra base de profesionales para futuras producciones. El registro no representa una promesa de contratación.',nameLabel:'Nombre completo',whatsappLabel:'WhatsApp',emailLabel:'E-mail',cityLabel:'Ciudad',stateLabel:'Estado',instagramLabel:'Instagram',rolesLabel:'Áreas de trabajo',rolesPlaceholder:'Producción, foto, bar, diseño...',portfolioLabel:'Portafolio',portfolioPlaceholder:'https://',availabilityLabel:'Disponibilidad / observaciones',submitLabel:'Enviar registro',successMessage:'Registro recibido. GTRZ se pondrá en contacto cuando exista una oportunidad compatible.',errorMessage:'No fue posible enviar. Inténtalo nuevamente.'},
    partnershipPage:{seoTitle:'Alianzas — GTRZ',eyebrow:'GTRZ · ALIANZAS',title:'CONSTRUYAMOS ALGO JUNTOS.',intro:'Espacios, marcas, artistas, proveedores y proyectos que quieran crear una experiencia con GTRZ.',contactNameLabel:'Tu nombre',companyNameLabel:'Empresa / proyecto',typeLabel:'Tipo de alianza',typePlaceholder:'—',venueOption:'Espacio / casa',brandOption:'Marca / patrocinio',artistOption:'Artista / proyecto cultural',supplierOption:'Proveedor',otherOption:'Otro',cityLabel:'Ciudad',emailLabel:'E-mail',whatsappLabel:'WhatsApp',messageLabel:'Cuéntanos la idea',submitLabel:'Enviar propuesta',successMessage:'Propuesta recibida. Nuestro equipo la revisará.',errorMessage:'No fue posible enviar. Inténtalo nuevamente.'},
    eventPage:{backLabel:'GTRZ',dateLabel:'FECHA',venueLabel:'LUGAR',aboutLabel:'Sobre el evento',lineupEyebrow:'GTRZ',lineupTitle:'LINE-UP.',ticketsEyebrow:'Entradas',ticketsTitle:'ELIGE TU ENTRADA.',availableLabel:'DISPONIBLE',draftLabel:'PRÓXIMAMENTE',soldOutLabel:'AGOTADO',closedLabel:'CERRADO',buyLabel:'Comprar',noTickets:'Las entradas todavía no están disponibles.',notFoundTitle:'ESTE EVENTO NO ESTÁ DISPONIBLE.',notFoundCta:'VOLVER A GTRZ'},
    popup:{multiHeader:'Eventos GTRZ disponibles',singleHeader:'Hay un evento activo en GTRZ',closeLabel:'Cerrar',eyebrow:'Agenda abierta',multiTitleLine1:'HAY GTRZ',multiTitleLine2:'EN MÁS DE UNA',multiTitleAccent:'CIUDAD.',singleTitleLine1:'HAY GTRZ',singleTitleLine2:'EN TU',singleTitleAccent:'CIUDAD.',multiBody:'Elige la ciudad y entra directamente a la página del evento.',singleFallbackBody:'Consulta fecha, lugar y entradas disponibles.',soldOutLabel:'Agotado',eventCta:'Ver evento y entradas',continueLabel:'Continuar en el sitio institucional'}
  }
};

export function getPublicCopy(settings:SiteSettings|undefined,locale:Locale,group:string){
  const copy={...(publicCopyDefaults[locale]?.[group]||{}),...((settings?.copy as any)?.[locale]?.[group]||{})};
  if(group==='eventPage'){
    if(typeof copy.backLabel==='string')copy.backLabel=copy.backLabel.replace(/^\s*[←↩]+\s*/u,'');
    const legacyNotFound=new Set(['EVENTO NÃO ENCONTRADO.','EVENTO NÃO ENCONTRADO','EVENTO NO ENCONTRADO.','EVENTO NO ENCONTRADO']);
    if(legacyNotFound.has(String(copy.notFoundTitle||'').trim().toUpperCase()))copy.notFoundTitle=publicCopyDefaults[locale].eventPage.notFoundTitle;
    if(String(copy.notFoundCta||'').trim().toUpperCase()==='GTRZ')copy.notFoundCta=publicCopyDefaults[locale].eventPage.notFoundCta;
  }
  return copy;
}
