import { useEffect,useMemo,useState } from 'react';
import { api } from '../../lib/api';
import { Empty,Metric,Notice,Panel } from '../../components/StateViews';
import { Icon } from '../../components/Icons';

type View='overview'|'sources'|'links'|'campaigns';
const metricLabels:Record<string,string>={page_view:'Page views',ticket_click:'Cliques em ingressos',popup_view:'Visualizações de popup',popup_click:'Cliques no popup',cta_click:'Cliques em CTA',instagram_click:'Cliques no Instagram',form_submit:'Formulários enviados',section_view:'Seções visualizadas',scroll_50:'Scroll 50%',scroll_90:'Scroll 90%'};
function total(rows:any[],metric:string,days=30){const cutoff=new Date();cutoff.setDate(cutoff.getDate()-days);const iso=cutoff.toISOString().slice(0,10);return rows.filter(r=>r.metric===metric&&r.day>=iso).reduce((sum,r)=>sum+Number(r.value||0),0)}
function compact(value:number){return new Intl.NumberFormat('pt-BR',{notation:value>999?'compact':'standard',maximumFractionDigits:1}).format(value)}

export function Analytics(){
  const [data,setData]=useState<any>({daily:[],sources:[],links:[],campaigns:[]});const [dashboard,setDashboard]=useState<any>({});const [view,setView]=useState<View>('overview');const [error,setError]=useState('');const [range,setRange]=useState<30|90>(30);const [loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);setError('');try{const [a,d]=await Promise.all([api<any>('/api/admin/analytics/overview'),api<any>('/api/admin/dashboard')]);setData(a);setDashboard(d)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load();},[]);
  const stats=useMemo(()=>({page:total(data.daily,'page_view',range),ticket:total(data.daily,'ticket_click',range),popupViews:total(data.daily,'popup_view',range),popupClicks:total(data.daily,'popup_click',range),cta:total(data.daily,'cta_click',range),forms:total(data.daily,'form_submit',range)}),[data.daily,range]);
  const conversion=stats.page?Math.min(100,(stats.ticket/stats.page)*100):0;
  const popupCtr=stats.popupViews?Math.min(100,(stats.popupClicks/stats.popupViews)*100):0;
  const dailyChart=useMemo(()=>{const cutoff=new Date();cutoff.setDate(cutoff.getDate()-(range-1));const map=new Map<string,number>();for(let i=0;i<range;i++){const d=new Date(cutoff);d.setDate(cutoff.getDate()+i);map.set(d.toISOString().slice(0,10),0)}for(const row of data.daily||[])if(row.metric==='page_view'&&map.has(row.day))map.set(row.day,(map.get(row.day)||0)+Number(row.value||0));const values=[...map.entries()].map(([day,value])=>({day,value}));const max=Math.max(1,...values.map(x=>x.value));return values.map(x=>({...x,pct:(x.value/max)*100}))},[data.daily,range]);
  const selectedRows=view==='sources'?data.sources:view==='links'?data.links:data.campaigns;
  const maxRank=Math.max(1,...(selectedRows||[]).map((r:any)=>Number(r.visitors||0)));
  const topMetrics=useMemo(()=>{const map=new Map<string,number>();const cutoff=new Date();cutoff.setDate(cutoff.getDate()-range);const iso=cutoff.toISOString().slice(0,10);for(const row of data.daily||[])if(row.day>=iso)map.set(row.metric,(map.get(row.metric)||0)+Number(row.value||0));return [...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10)},[data.daily,range]);
  return <div className="module-stack"><Panel title="Analytics" eyebrow="Aquisição e comportamento" description="Sessões anônimas, origem, campanhas e sinais de conversão consolidados no GTRZ Control." action={<div className="range-switch"><button className={range===30?'active':''} onClick={()=>setRange(30)}>30 dias</button><button className={range===90?'active':''} onClick={()=>setRange(90)}>90 dias</button><button className="icon-button" onClick={load} title="Atualizar"><Icon name="refresh" size={15}/></button></div>}>
    {error&&<Notice tone="error">{error}</Notice>}
    <div className="metric-grid analytics-metrics"><Metric label="Visitantes únicos" value={loading?'…':dashboard.uniqueVisitors30d??0} detail="únicos · 30 dias" icon="people" tone="red"/><Metric label="Page views" value={loading?'…':compact(stats.page)} detail={`últimos ${range} dias`} icon="eye"/><Metric label="Cliques em ingressos" value={loading?'…':compact(stats.ticket)} detail={`${conversion.toFixed(1)}% sobre page views`} icon="link" tone="good"/><Metric label="CTR do popup" value={loading?'…':`${popupCtr.toFixed(1)}%`} detail={`${compact(stats.popupClicks)} de ${compact(stats.popupViews)} views`} icon="events"/></div>
    <div className="segment-tabs analytics-tabs"><button className={view==='overview'?'active':''} onClick={()=>setView('overview')}><Icon name="analytics" size={16}/> Visão geral</button><button className={view==='sources'?'active':''} onClick={()=>setView('sources')}><Icon name="globe" size={16}/> Origens</button><button className={view==='links'?'active':''} onClick={()=>setView('links')}><Icon name="link" size={16}/> Links</button><button className={view==='campaigns'?'active':''} onClick={()=>setView('campaigns')}><Icon name="marketing" size={16}/> Campanhas</button></div>
    {view==='overview'&&<div className="analytics-overview"><section className="analytics-chart-card"><div className="chart-head"><div><small>TRÁFEGO</small><h3>Page views por dia</h3></div><strong>{compact(stats.page)}</strong></div>{dailyChart.some(x=>x.value>0)?<div className={`bar-chart range-${range}`}>{dailyChart.map((point,i)=><div className="bar-column" key={point.day} title={`${new Date(point.day+'T12:00:00').toLocaleDateString('pt-BR')}: ${point.value}`}><div className="bar-value" style={{height:`${Math.max(point.value?3:0,point.pct)}%`}}/><span>{range===30?(i%5===0?new Date(point.day+'T12:00:00').getDate():''):i%15===0?new Date(point.day+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}):''}</span></div>)}</div>:<Empty icon="analytics">Ainda não há page views no período selecionado.</Empty>}</section><section className="analytics-signals"><div className="chart-head"><div><small>SINAIS</small><h3>Eventos de comportamento</h3></div></div>{topMetrics.length?<div className="signal-list">{topMetrics.map(([metric,value])=><article key={metric}><div><strong>{metricLabels[metric]||metric.replaceAll('_',' ')}</strong><span>{metric}</span></div><b>{compact(value)}</b></article>)}</div>:<Empty>Sem eventos agregados.</Empty>}</section></div>}
    {view!=='overview'&&<section className="ranking-card"><div className="chart-head"><div><small>{view==='sources'?'AQUISIÇÃO':view==='links'?'DISTRIBUIÇÃO':'CAMPANHAS'}</small><h3>{view==='sources'?'De onde chegam as pessoas':view==='links'?'Links que trazem sessões':'Campanhas atribuídas'}</h3></div><span>visitantes únicos · 30d</span></div>{selectedRows?.length?<div className="ranking-list">{selectedRows.map((row:any,index:number)=>{const name=view==='sources'?(row.source||'direct'):view==='links'?(row.tracking_link||'—'):(row.campaign||'—');const visitors=Number(row.visitors||0);return <article key={`${name}-${index}`}><span className="ranking-position">{String(index+1).padStart(2,'0')}</span><div className="ranking-copy"><div><strong>{name}</strong><b>{visitors}</b></div><span className="ranking-track"><i style={{width:`${Math.max(2,(visitors/maxRank)*100)}%`}}/></span></div></article>})}</div>:<Empty icon={view==='sources'?'globe':view==='links'?'link':'marketing'}>{view==='sources'?'Ainda não há dados de aquisição.':view==='links'?'Nenhum link rastreável trouxe sessões ainda.':'Nenhuma campanha atribuída ainda.'}</Empty>}</section>}
    <div className="analytics-privacy"><Icon name="system" size={18}/><div><strong>Medição com privacidade</strong><span>O painel trabalha com sessões anonimizadas e agregados. IP bruto não é exibido nem usado como “visitante”.</span></div></div>
  </Panel></div>;
}
