import { useEffect,useMemo,useState } from 'react';
import { api } from '../../lib/api';
import { Badge,Empty,Notice,Panel } from '../../components/StateViews';
import { Icon } from '../../components/Icons';

const statuses=[['new','Novo'],['reviewing','Em análise'],['contacted','Contato realizado'],['negotiating','Em negociação'],['won','Aprovado'],['lost','Recusado']] as const;
const tone=(status:string):'neutral'|'red'|'green'|'yellow'|'blue'=>status==='won'?'green':status==='new'?'red':status==='reviewing'?'yellow':status==='contacted'||status==='negotiating'?'blue':'neutral';
const money=(cents?:number|null)=>typeof cents==='number'?(cents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—';
const parseJson=(v:any)=>{try{const x=JSON.parse(v||'[]');return Array.isArray(x)?x:[]}catch{return []}};

export function Commercial(){
  const [items,setItems]=useState<any[]>([]);const [selected,setSelected]=useState<any|null>(null);const [notes,setNotes]=useState('');const [message,setMessage]=useState('');const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [busy,setBusy]=useState(false);const [nextContactAt,setNextContactAt]=useState('');const [potentialValue,setPotentialValue]=useState('');
  const [config,setConfig]=useState<any>({whatsapp:'',partnerTypes:[],proposalTypes:[]});const [configBusy,setConfigBusy]=useState(false);
  const load=()=>api<any>('/api/admin/partnerships').then(r=>setItems(r.results||[])).catch(e=>setMessage(e.message));
  const loadConfig=()=>api<any>('/api/admin/partnership-config').then(setConfig).catch(e=>setMessage(e.message));
  useEffect(()=>{load();loadConfig();},[]);
  const update=async(id:string,patch:any)=>{setBusy(true);try{await api(`/api/admin/partnerships/${id}`,{method:'PATCH',body:JSON.stringify(patch)});await load();if(selected?.id===id)setSelected((s:any)=>({...s,...patch}));setMessage('Oportunidade atualizada.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
  const remove=async(x:any)=>{const label=x.trade_name||x.company_name||x.contact_name||'esta proposta';if(!confirm(`Excluir permanentemente ${label}? Esta ação remove a resposta do formulário e o PDF anexado, se houver, e não pode ser desfeita.`))return;setBusy(true);try{await api(`/api/admin/partnerships/${x.id}`,{method:'DELETE'});setSelected(null);setNotes('');setNextContactAt('');setPotentialValue('');await load();setMessage(`${label} foi excluído permanentemente.`)}catch(e:any){setMessage(`Erro ao excluir proposta: ${e.message}`)}finally{setBusy(false)}};
  const saveConfig=async()=>{setConfigBusy(true);try{const saved=await api<any>('/api/admin/partnership-config',{method:'PATCH',body:JSON.stringify(config)});setConfig(saved);setMessage('Configuração de parcerias salva.')}catch(e:any){setMessage(e.message)}finally{setConfigBusy(false)}};
  const open=(x:any)=>{setSelected(x);setNotes(x.notes||'');setNextContactAt(x.next_contact_at?.slice(0,16)||'');setPotentialValue(typeof x.potential_value_cents==='number'?String(x.potential_value_cents/100):'')};
  const filtered=useMemo(()=>items.filter(x=>(filter==='all'||x.status===filter)&&(!query||`${x.trade_name||x.company_name||''} ${x.contact_name||''} ${x.city||''} ${x.partner_type||''} ${x.proposal_title||''}`.toLowerCase().includes(query.toLowerCase()))),[items,filter,query]);
  const proposalTypes=selected?parseJson(selected.proposal_types_json):[];
  return <div className="module-stack">
    <Panel title="Parcerias" eyebrow="Comercial" description="Pipeline de marcas, espaços, empresas, fornecedores, projetos e oportunidades comerciais.">
      <div className="pipeline-board">{statuses.slice(0,5).map(([value,label])=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(filter===value?'all':value)}><span>{label}</span><strong>{items.filter(x=>x.status===value).length}</strong></button>)}</div>
      {message&&<Notice tone={message.toLowerCase().includes('erro')?'error':'success'}>{message}</Notice>}
      <div className="split-admin-view commercial-split"><div className="lead-list-pane"><div className="toolbar"><label className="search-box"><Icon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar organização, pessoa, cidade ou proposta…"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option>{statuses.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>{filtered.length?<div className="lead-list commercial-list">{filtered.map(x=><button key={x.id} className={selected?.id===x.id?'active':''} onClick={()=>open(x)}><div><strong>{x.trade_name||x.company_name||x.contact_name}</strong><span>{x.partner_type||x.partnership_type} · {x.city||'cidade não informada'}</span><small>{x.proposal_title||x.contact_name}</small></div><Badge tone={tone(x.status)}>{statuses.find(([s])=>s===x.status)?.[1]||x.status}</Badge></button>)}</div>:<Empty icon="commercial">Nenhuma proposta corresponde aos filtros.</Empty>}</div>
      <div className="lead-detail-pane">{selected?<><div className="lead-detail-head"><div><Badge tone={tone(selected.status)}>{statuses.find(([s])=>s===selected.status)?.[1]||selected.status}</Badge><h3>{selected.trade_name||selected.company_name||selected.contact_name}</h3><p>{selected.partner_type||selected.partnership_type} · recebida {new Date(selected.created_at).toLocaleString('pt-BR')}</p></div><button className="icon-button" onClick={()=>setSelected(null)}><Icon name="close"/></button></div>
      <div className="contact-actions">{selected.whatsapp&&<a className="button primary" href={`https://wa.me/${String(selected.whatsapp).replace(/\D/g,'')}`} target="_blank" rel="noreferrer">WhatsApp <Icon name="external" size={14}/></a>}{selected.email&&<a className="button" href={`mailto:${selected.email}`}>E-mail</a>}{selected.website_url&&<a className="button" href={selected.website_url} target="_blank" rel="noreferrer">Site</a>}</div>
      <div className="lead-info-grid"><div><span>Contato</span><strong>{selected.contact_name||'—'}</strong></div><div><span>Cargo / função</span><strong>{selected.contact_role||'—'}</strong></div><div><span>E-mail</span><strong>{selected.email||'—'}</strong></div><div><span>WhatsApp</span><strong>{selected.whatsapp||'—'}</strong></div><div><span>Parceiro</span><strong>{selected.partner_type||'—'}</strong></div><div><span>Segmento</span><strong>{selected.segment||'—'}</strong></div><div><span>Razão social</span><strong>{selected.legal_name||'—'}</strong></div><div><span>CNPJ / CPF</span><strong>{selected.tax_id||'—'}</strong></div><div><span>Localização</span><strong>{[selected.city,selected.state].filter(Boolean).join(' · ')||'—'}</strong></div><div><span>Endereço</span><strong>{[selected.street,selected.address_number,selected.neighborhood,selected.postal_code].filter(Boolean).join(' · ')||'—'}</strong></div><div><span>Capacidade</span><strong>{selected.venue_capacity||'—'}</strong></div><div><span>Instagram</span><strong>{selected.instagram_url||'—'}</strong></div></div>
      <div className="proposal-message"><span>TIPOS DE PARCERIA</span><p>{proposalTypes.length?proposalTypes.join(' · '):(selected.partnership_type||'—')}</p></div><div className="proposal-message"><span>TÍTULO</span><p>{selected.proposal_title||'—'}</p></div><div className="proposal-message"><span>RESUMO DA IDEIA</span><p>{selected.message||'—'}</p></div><div className="proposal-message"><span>O QUE OFERECE</span><p>{selected.offer_text||'—'}</p></div><div className="proposal-message"><span>O QUE ESPERA DA GTRZ</span><p>{selected.expectation_text||'—'}</p></div>
      <div className="lead-info-grid"><div><span>Investimento</span><strong>{selected.investment_status||'—'}</strong></div><div><span>Valor informado</span><strong>{money(selected.investment_value_cents)}</strong></div><div><span>Período</span><strong>{[selected.starts_at,selected.ends_at].filter(Boolean).join(' até ')||'—'}</strong></div><div><span>Arquivo</span><strong>{selected.proposal_file_name||'NÃO ANEXADO'}</strong></div><div><span>Link de apresentação</span><strong>{selected.presentation_url||'—'}</strong></div><div><span>LGPD</span><strong>{selected.privacy_accepted?`ACEITE · V. ${selected.privacy_notice_version||'1.0'}`:'REGISTRO ANTIGO'}</strong></div></div>
      {selected.observations&&<div className="proposal-message"><span>OBSERVAÇÕES</span><p>{selected.observations}</p></div>}
      <div className="form-grid-public"><label className="field"><span>Etapa do pipeline</span><select value={selected.status} onChange={e=>setSelected((s:any)=>({...s,status:e.target.value}))}>{statuses.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="field"><span>Próximo contato</span><input type="datetime-local" value={nextContactAt} onChange={e=>setNextContactAt(e.target.value)}/></label><label className="field"><span>Valor potencial (R$)</span><input inputMode="decimal" value={potentialValue} onChange={e=>setPotentialValue(e.target.value)}/></label></div><label className="field"><span>Notas internas</span><textarea className="tall" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Próximo passo, contraproposta, responsáveis, condições…"/></label><div className="row-actions"><button className="danger" disabled={busy} onClick={()=>remove(selected)}><Icon name="trash" size={16}/> Excluir proposta</button><button className="primary" disabled={busy} onClick={()=>update(selected.id,{status:selected.status,notes,nextContactAt:nextContactAt||null,potentialValueCents:potentialValue?Math.round(Number(potentialValue.replace(',','.'))*100):null})}><Icon name="save" size={16}/> Salvar oportunidade</button></div></>:<div className="settings-empty"><Icon name="commercial" size={30}/><strong>Selecione uma proposta</strong><span>Abra uma oportunidade para consultar o dossiê comercial e administrar o pipeline.</span></div>}</div></div>
    </Panel>
    <Panel title="Configuração do formulário" eyebrow="Parcerias" description="Defina o WhatsApp de destino e as opções exibidas no formulário público."><div className="form-grid-public"><label className="field"><span>WhatsApp GTRZ</span><input value={config.whatsapp||''} onChange={e=>setConfig((s:any)=>({...s,whatsapp:e.target.value}))} placeholder="5581XXXXXXXXX"/></label><label className="field"><span>Tipos de parceiro · uma opção por linha</span><textarea className="tall" value={(config.partnerTypes||[]).join('\n')} onChange={e=>setConfig((s:any)=>({...s,partnerTypes:e.target.value.split('\n').map((x:string)=>x.trim()).filter(Boolean)}))}/></label><label className="field"><span>Tipos de parceria · uma opção por linha</span><textarea className="tall" value={(config.proposalTypes||[]).join('\n')} onChange={e=>setConfig((s:any)=>({...s,proposalTypes:e.target.value.split('\n').map((x:string)=>x.trim()).filter(Boolean)}))}/></label></div><button className="primary" disabled={configBusy} onClick={saveConfig}><Icon name="save" size={16}/> Salvar configuração</button></Panel>
  </div>;
}